split workflow in jobs and add release workflow (#18)
* split workflow in jobs and add release workflow #17

split workflow into jobs
update README

* split workflow in jobs and add release workflow #17

fix check

* split workflow in jobs and add release workflow #17

add release workflow dispatch

* fix working directory

split workflow in jobs and add release workflow #17

* release job disable if no tag v*.*.*

split workflow in jobs and add release workflow #17
[ci skip]

diff --git a/release b/release
--- a/release
+++ b/release
@@ -12,6 +12,19 @@ create_release() {
         exit 1
     fi
 
+    # check if the tag already exists
+    if git rev-parse "$VERSION" >/dev/null 2>&1; then
+        echo "Error: Tag $VERSION already exists."
+        exit 1
+    fi
+
+    # check the format of the version number
+    if [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-z]+\.[0-9]+)?$ ]]; then
+        echo "Error: Version number should be in the format vx.y.z or vx.y.z-pre.a."
+        exit 1
+    fi
+
+    
     # Tag the repository with the provided version
     git tag -a "$VERSION" -m "Release $VERSION"
 
